name: CI - Build code analysis for PRs on maaster branch

on:
    pull_request:
        branches:
        - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x

        - name: Build with code analysis
          run: dotnet build -warnaserror DBTestCICD.sqlproj /p:RunSqlCodeAnalysis=true
          working-directory: DBTestCICD