name: deploy on testing from main

on:
  push:
    branches:
      - main
    paths:
      - 'DBTestCICD/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout code'
        uses: actions/checkout@v4

      # build the project into a dacpac file
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-vesion: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore

        # generate a deployment report
      - name: 'Deploy dacpac'
        run: sqlpackage /a:deployemntreport /sf:'bin/Debug/DBTestCICD.dacpac' /tcs:"${{ secrets.TESTING_CONNECTION_STRING }};" /dsp:'deployment-script-testing.sql'
        working-directory: DBTestCICD
        
      # save the deployment script as an artifact
      - name: 'Save deployment script'
        uses: actions/upload-artifact@v4
        with:
          name: deployment-script
          path: DBTestCICD/deployment-script-testing.sql