name: deploy on development from main

on:
  workflow_call:
    inputs:
      tenant_name:
        description: Tenant name to deploy
        type: string
        required: true
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    paths:
      - 'DBTestCICD/**'
    
env: 
  environment: 'development'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout code'
        uses: actions/checkout@v4

      # build the project into a dacpac file
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
        #run: dotnet build DBTestCICD.sqlproj

       #- name: Run SQL scripts
        #run: |
          # Example: Use sqlcmd to execute scripts from the SQL scripts folder
         # sqlcmd -S <server_name> -d <database_name> -U <username> -P <password> -i "SQL Scripts/*.sql"
          # Or, if you're deploying a DACPac file:
          # sqlpackage /a:Deploy /p:DatabaseName= <database_name> /p:TargetDatabaseServer=<server_name> /p:TargetDatabaseUser= <username> /p:TargetDatabasePassword=<password> /S:<dacpac_file_path> /n:<database_name> /f:deploy.sql
          # OR dacfile another command
          #sqlpackage /Action:Publish /SourceFile:bin/Debug/MyDatabaseProject.dacpac /TargetConnectionString:{yourconnectionstring}

      # deploy the sql project to development
      - name: 'Deploy dacpac'
        run: sqlpackage /a:Publish /sf:'bin/Debug/DBTestCICD.dacpac' /tcs:"${{ vars.DEV_CONNECTION_STRING_DATASOURCE }};Initial Catalog=${{ inputs.tenant_name }} ;Persist Security Info=True;${{ vars.DEV_CONNECTION_STRING_USERID }};${{ vars.DEV_CONNECTION_STRING_PASSWORD }};TrustServerCertificate=True;"  /dsp:'deployment-script-development.sql'
        working-directory: DBTestCICD

      # save the deployment script as an artifact
      - name: 'Save deployment script'
        uses: actions/upload-artifact@v4
        with:
          name: deployment-script
          path: DBTestCICD/deployment-script-development.sql

